import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import Portal from "@/components/Portal/Portal";
import "normalize.css";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body className={roboto.className}>
        <Header />
        <main>
          {children}
          <Portal />
        </main>
        <Footer />
      </body>
    </html>
  );
}
